# Filename: qtn.gr
#
# You can customize by copying those parameters that you want to change
# into a qtn.gr file in your working directory or ~/lib.
#
# Stuff not automated yet
#
# Title
#
#@title " "
#@subtitle " "
#
# Y axis
#
@yaxis label "-Log(P-Value)"
#@yaxis tick major 1
#@yaxis tick minor 0

# The following is automated and will mess up labels if overridden
#@world ymax 11
#@world ymin -1
#@yaxis ticklabel start type spec
#@yaxis ticklabel start 0
#@yaxis ticklabel stop type spec
#@yaxis ticklabel stop 8
# Use the following if all labels are single digit
#@yaxis label place spec
#@yaxis label place 0.043,0
#
# X axis
#
@xaxis label "Nucleotide Position"
@xaxis tick major 2500
@xaxis tick minor 500
@xaxis ticklabel start type spec
@xaxis ticklabel start -2500
# Fonts Available:
# 0:Times-Roman 1:Times-Bold 2:Times-Italic 3:Times-BoldItalic
# 4:Helvetica 5:Helvetica-Bold 6:Helvetica-Oblique 7:Helvetica-BoldOblique

# Colors Available:
# 0:White 1:Black 2:Red 3:Green 4:Blue 5:Yellow 6:Brown 7:Gray 8:Violet 9:Cyan
# 10:Magenta 11:Orange 12:Indigo 13:Maroon 14:Turquoise 15:Green4
#
# -

# Title and Subtitle setup
#
#@title ""
@title font 0
@title color 1
@title size 1.500000
@title linewidth 1
#
#@subtitle ""
@subtitle font 2
@subtitle color 1
@subtitle linewidth 1
#
# X axis
#
@xaxis label char size 1.500000
@xaxis label linewidth 1
@xaxis label font 1
@xaxis ticklabel font 0
@xaxis tick major linewidth 3
@xaxis tick minor linewidth 3
@frame linewidth 6
#
# Y axis
#
# The yaxis label is read from multipoint*.out file since it might be
# LOD or S-LOD.  However, you can override it by uncommenting the following
# line and changing LOD to whatever you want.
#@yaxis label "LOD"
#
# Special placement is used for the Y axis label if LOD<10 (1-digit)
#  because the auto placement puts the label too far right with 1 digit.
#   Unfortunately, this causes the postscript Y axis label to be slightly left.
#   Uncomment the next option line to restore the auto placement feature,
#     or uncomment the following lines and adjust the number as you wish
#@yaxis label place auto
#

@yaxis label char size 1.500000
@yaxis label linewidth 1
@yaxis label font 1
@yaxis ticklabel font 0
@yaxis tick major linewidth 3
@yaxis tick minor linewidth 3
#
# Marker label settings
#
@string font 4
@string linewidth 1
@string color 1
@string just 0
#
# Marker tick and line settings
#
@line linewidth 2
@line color 1
#
# Set (i.e. the plotted curve) settings
#   By default, the set number used matches the chromosome number
#   Overlays are done with the last unused set (starting from 29).
#   Set 0 is used to plot NaN's if there are any
#     This set is drawn as symbols, by default X is used
#     linestyle 0 means do not connect points with a line
#
#   Symbols available:  (NOTE: THE DOCUMENTATION WAS OFF BY 1)
#   1:None  2:Circle  3:Square  4:Diamond  5:Triangle up  6:Triangle left
#   7:Triangle down  8:Triangle right  9:Plus  10:X  11:Star
#
@s1 linewidth 6
@s0 color 1
@s1 color 2
@s1 symbol 2
@s1 symbol size 1.0
@s1 symbol fill 1
@s1 linestyle 1
#
# To clarify the meaning of the NaN symbols, a legend is drawn.
#
@legend string 0 "  Convergence or Boundary Error"
@legend font 0
@legend char size 1.0
@legend linewidth 3
@legend color 1
# length determines how close to symbol legend box begins
@legend length 1
#
@legend box linewidth 3
@legend box color 1
#
# Legend position must be done by program, however it can be modified later
# with xmgr gui.
#
#
# Don't mess with these; will foul up markers
#@world xmin -1100
#@world xmax 1100
#@xaxis ticklabel start type spec
#@xaxis ticklabel start -1000
